name: MercadoFacil
packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift.git
    exactVersion: 2.2.0
options:
  bundleIdPrefix: com.seuuusario.mercadofacil
targets:
  MercadoFacil:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Models
      - path: Views
      - path: ViewModels
      - path: Components
      - path: Services
      - path: Utilities
      - path: MercadoFacilApp.swift
      - path: Assets.xcassets
    dependencies:
      - package: Supabase
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.seuuusario.mercadofacil
        CODE_SIGN_IDENTITY: "Apple Distribution"
        DEVELOPMENT_TEAM: 3YB4FZDQ82
        PROVISIONING_PROFILE_SPECIFIER: "MercadoFacil Oficial Profile"
        CODE_SIGN_STYLE: Manual
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        NSLocationWhenInUseUsageDescription: "Precisamos da sua localização para exibir produtos na sua região."
        CFBundleDevelopmentRegion: "pt-BR"
        CFBundleAllowMixedLocalizations: true
        CFBundleLocalizations:
          - "pt-BR"
