name: MercadoFacil
packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift.git
    exactVersion: 2.2.0
options:
  bundleIdPrefix: com.achou.com
targets:
  MercadoFacil:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Models
      - path: Views
      - path: ViewModels
      - path: Components
      - path: Services
      - path: Utilities
      - path: MercadoFacilApp.swift
      - path: Assets.xcassets
    dependencies:
      - package: Supabase
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.achou.com
        DEVELOPMENT_TEAM: 3YB4FZDQ82
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        CURRENT_PROJECT_VERSION: 2
        MARKETING_VERSION: 1.0
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        NSLocationWhenInUseUsageDescription: "Precisamos da sua localização para exibir produtos na sua região."
        CFBundleDevelopmentRegion: "pt-BR"
        CFBundleAllowMixedLocalizations: true
        CFBundleLocalizations:
          - "pt-BR"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
