name: Deploy to TestFlight

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.3.app || sudo xcode-select -switch /Applications/Xcode_15.4.app

    - name: Install Xcodegen
      run: brew install xcodegen

    - name: Generate Xcode Project
      run: xcodegen generate

    - name: Install the Apple certificate and provisioning profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: "123456"
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

    - name: Build Archive
      run: |
        set -o pipefail
        xcodebuild archive \
          -project MercadoFacil.xcodeproj \
          -scheme MercadoFacil \
          -archivePath $RUNNER_TEMP/MercadoFacil.xcarchive \
          -sdk iphoneos \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          clean archive DEVELOPMENT_TEAM=3YB4FZDQ82 PRODUCT_BUNDLE_IDENTIFIER=com.seuuusario.mercadofacil CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER='MercadoFacil Oficial Profile' CODE_SIGN_IDENTITY='Apple Distribution'

    - name: Export IPA
      run: |
        cat <<EOF > ExportOptions.plist
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>3YB4FZDQ82</string>
            <key>provisioningProfiles</key>
            <dict>
                <key>com.seuuusario.mercadofacil</key>
                <string>MercadoFacil Oficial Profile</string>
            </dict>
        </dict>
        </plist>
        EOF
        
        xcodebuild -exportArchive \
          -archivePath $RUNNER_TEMP/MercadoFacil.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $RUNNER_TEMP/export

    - name: Upload IPA Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: MercadoFacil-IPA
        path: $RUNNER_TEMP/export/MercadoFacil.ipa

    - name: Upload to TestFlight via Fastlane
      env:
        APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
        APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.appstoreconnect/private_keys
        echo -n "$APPSTORE_PRIVATE_KEY" | base64 --decode > ~/.appstoreconnect/private_keys/AuthKey_${APPSTORE_KEY_ID}.p8
        
        # We don't need brew install fastlane, it's preinstalled on macos-14
        
        cat <<EOF > Fastfile
        default_platform(:ios)
        platform :ios do
          lane :upload_testflight do
            app_store_connect_api_key(
              key_id: ENV["APPSTORE_KEY_ID"],
              issuer_id: ENV["APPSTORE_ISSUER_ID"],
              key_filepath: "$HOME/.appstoreconnect/private_keys/AuthKey_${ENV['APPSTORE_KEY_ID']}.p8",
              in_house: false
            )
            pilot(
              ipa: "$RUNNER_TEMP/export/MercadoFacil.ipa",
              skip_waiting_for_build_processing: true,
              app_identifier: "com.seuuusario.mercadofacil",
              
            )
          end
        end
        EOF
        
        fastlane ios upload_testflight



